application:
  subdomain: nullbr115
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://nullbr115:8115
services:
  nullbr115:
    # upstream: gravityle/nullbr115:0.2.1.9
    image: docker.1ms.run/gravityle/nullbr115:0.2.1.9
    binds:
      - /lzcapp/var/config:/config
      - /lzcapp/var/media:/media
    environment:
      - API_KEY={{.U.nullbr_api_key}}
