package: lazycat.coummunity.app.nullbr115
version: 0.2.19
name: Nullbr115
description: "Nullbr115是一个海量资源库项目,支持ed2k/磁力离线下载，支持115、123网盘转存"
min_os_version: "1.5.0"
homepage: https://nullbr.online
author: nullbr
locales:
  zh:
    description: "Nullbr115是一个海量资源库项目,支持ed2k/磁力离线下载，支持115、123网盘转存"
    name: Nullbr115
  en:
    description: "Nullbr115 is a massive resource library project supporting ed2k/magnet offline downloads and 115/123 pan transfers"
    name: Nullbr115
